name: Deploy to Forge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Forge Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy
        run: curl -f "${{ secrets.FORGE_DEPLOY_HOOK }}"
